services:
  postgres:
    image: postgres:16-alpine
    container_name: artere-postgres
    environment:
      POSTGRES_DB: arteredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_arter:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d arteredb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - artere-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: artere-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@artere.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - artere-network
    restart: unless-stopped

volumes:
  postgres_data_arter:

networks:
  artere-network:
    driver: bridge
